
[labelparameters]
LABEL_CLASSES = ['civilian', 'military']  # Binary class labels

[modelparameters]
EPOCHS = 1000
LEARNING_RATE = 0.001
BATCH_SIZE = 128
HIDDEN_LAYER_SIZES = [512, 256]
NUM_CLASSES = 2
SEED = 386

[dataset_filenames]
train_labels = 'train_labels.csv'
test_labels = 'test_labels.csv'
